### ISSUE TITLE
What does --no-noplot do?

### ISSUE THREAD

**Issue by milesgranger** [flikka/flass#1]
If I use `--no-noplot` is that the same as `--plot`? Two negatives make a positive, yes? Or is it more like _"No, seriously, don't make a plot"_

https://github.com/flikka/flass/blob/3e614213e4c8170cb8213ec9190d52136f1a3d95/flass/cli.py#L13

**Comment by flikka** [comment]
Exactly! It is like: No, no, please no plot!

**Comment by milesgranger** [comment]
Thank you for your speedy response. :rocket:

**Comment by flikka** [comment]
The customer is always right
